#include "visualLB.h"
#include <stdio.h>
#include "LBDefinitions.h"
#include "helper.h"
#include "computeCellValues.h"




void writeVtkOutput(const double * const collideField, const int * const flagField, const char * filename, int rank, unsigned int t, int *subdomain, int *proc) {
    char fn[80];
//    int len = xlength+2;
    // save filename as a combination of passed filename and timestep
    sprintf(fn, "%s.%i.%i.vtk", filename, rank, t);
    
    FILE *fp = NULL;
    fp = fopen(fn, "w");
    if (fp == NULL) {
        ERROR("Failed to open file!");
        return;
    }

    // write header
    fprintf(fp, "# vtk DataFile Version 2.0\n");
    fprintf(fp, "generated by CFD-lab course output \n");
    fprintf(fp, "ASCII\n\n");
    fprintf(fp, "DATASET STRUCTURED_GRID\n");
    fprintf(fp, "DIMENSIONS %d %d %d \n", subdomain[0], subdomain[1], subdomain[2]);
    fprintf(fp, "POINTS %d float\n\n", (subdomain[0]) * (subdomain[1]) * (subdomain[2]));
   
    // print lattice points
    double step = 1.0 / (xlength - 1); //TODO
    for (double x = 0; x <= subdomain[0]-1; x+=1) {
        for (double y = 0; y <= subdomain[1]-1; y+=1) {
            for (double z = 0; z <= subdomain[2]-1; z+=1) {
                fprintf(fp, "%f %f %f\n", x*step, y*step, z*step);
            }
        }
    }

    double density;
    double vel[D];
    const double *currentCell;

    // write density data
    fprintf(fp, "\nPOINT_DATA %d \n", (xlength) * (xlength) * (xlength));
    fprintf(fp, "SCALARS density float 1 \n");
    fprintf(fp, "LOOKUP_TABLE default \n");
    
    for (int x = 1; x < xlength+1; ++x) {
        for (int y = 1; y < xlength+1; ++y) {
            for (int z = 1; z < xlength+1; ++z) {
                currentCell = collideField + Q*( z*len*len + y*len + x);
                computeDensity(currentCell, &density);
                fprintf(fp, "%f\n", density);
            }
        }
    }

    // compute velocities for all cells
    fprintf(fp, "\nVECTORS velocity float\n");
    
    for (int x = 1; x < xlength+1; ++x) {
        for (int y = 1; y < xlength+1; ++y) {
            for (int z = 1; z < xlength+1; ++z) {
                currentCell = collideField + Q*( z*len*len + y*len + x );
                computeDensity(currentCell, &density);
                computeVelocity(currentCell, &density, vel);
                fprintf(fp, "%f %f %f\n", vel[0], vel[1], vel[2]);
            }
        }
    }

    // close the file
    if (fclose(fp)) {
        ERROR("Failed to close file!");
        return;
    }
}
