#include "visualLB.h"
#include <stdio.h>
#include "LBDefinitions.h"
#include "helper.h"
#include "computeCellValues.h"

void writeVtkOutput(const double * const collideField, const int * const flagField, const char * filename, unsigned int t, int xlength) {
    char fn[80];
    /* Save filename as a combination of passed filename and timestep */
    sprintf(fn, "%s.%i.vtk", filename, t);
    
    FILE *fp = fopen(fn, "w");
    if (fp == NULL) {
        ERROR("Failed to open file!");
        return;
    }
    
    fprintf(fp, "# vtk DataFile Version 2.0\n");
    fprintf(fp, "generated by CFD-lab course output \n");
    fprintf(fp, "ASCII\n\n");
    fprintf(fp, "DATASET STRUCTURED_GRID\n");
    fprintf(fp, "DIMENSIONS %d %d %d \n", xlength, xlength, xlength); //debug
    fprintf(fp, "POINTS %d float\n\n", (xlength) * (xlength) * (xlength)); //debug
   
    /* Print lattice points */
    double step = 1.0 / (xlength - 1);
    //printf("step is %f\n", step);
    double a, b, c;
    for (double x = 0; x <= xlength-1; x+=1) {
        for (double y = 0; y <= xlength-1; y+=1) {
            for (double z = 0; z <= xlength-1; z+=1) {
		a = x*step;
		b = y*step;
		c = z*step;
                fprintf(fp, "%f %f %f\n", a, b, c);
            }
        }
    }

    double density;
    double vel[D];
    const double *currentCell;
    
    fprintf(fp, "\nPOINT_DATA %d \n", (xlength) * (xlength) * (xlength));
    fprintf(fp, "SCALARS density float 1 \n");
    fprintf(fp, "LOOKUP_TABLE default \n");
    
    /* Compute density for each cell */
    for (int x = 1; x < xlength+1; ++x) {
        for (int y = 1; y < xlength+1; ++y) {
            for (int z = 1; z < xlength+1; ++z) {
                currentCell = collideField + Q*(z*xlength*xlength+y*xlength+x);/*with or without"&"??*/
                computeDensity(currentCell, &density);
                fprintf(fp, "%f\n", density);
            }
        }
    }

    fprintf(fp, "\nVECTORS velocity float\n");
    
    /* Compute (macroscopic) velocities for all cells */
    for (int x = 1; x < xlength+1; ++x) {
        for (int y = 1; y < xlength+1; ++y) {
            for (int z = 1; z < xlength+1; ++z) {
                currentCell = collideField + Q*(z*xlength*xlength+y*xlength+x);/*with or without"&"??*/
                computeDensity(currentCell, &density);
                computeVelocity(currentCell, &density, vel);
                fprintf(fp, "%f %f %f\n", vel[0], vel[1], vel[2]);
            }
        }
    }

    
    if (fclose(fp)) {
        ERROR("Failed to close file!");
        return;
    }
}
