#include <stdlib.h>
#include <stdio.h>
#include <mpi.h>
#include "mmult_def.h"

/* Matrix multiplication in parallel illustrated via a master-slave scheme.
 * Reads two matrices generated by the gen_matrix function and writes out the
 * result. */

int main(int argc, char **argv)
{
	int *m1, *m2, *rm;
	int matrix_size;
	int myrank;
	double t1, t2;

	if(argc != 4)
	{
		printf("\nusage:\n%s <matrix1 filename> <matrix2 filename> <resulting matrix filename>", argv[0]);
		exit(-1);
	}

	MPI_Init(&argc, &argv);
	MPI_Comm_rank(MPI_COMM_WORLD, &myrank);
				       

	if(myrank == 0)
	{
		m1 = (int *) read_file(argv[1], &matrix_size, MAT_NORM);	//read matrix file normal
		m2 = (int *) read_file(argv[2], &matrix_size, MAT_TURN);	//read matrix file turned
		t1 = MPI_Wtime();	
		rm = master(m1, m2, matrix_size);	//call algorithm
		t2 = MPI_Wtime();
		printf("\ntime: %f\n\n", t2-t1);
		write_file(argv[3], rm, matrix_size);

        	free(m1);
		free(m2);
	}	       
	else
	{
		slave();
	}
	
	MPI_Finalize();
	
	return 0;
}
